spring:
  application:
    name: authentication-api

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver  # Cambiar a PostgreSQL

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # Cambiar a dialecto PostgreSQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    jpa:
      repositories:
        enabled: true

  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /api

security:
  constant: ${SECURITY_CONSTANT}

frontend:
  url: ${FRONTEND_URL}

app:
  upload:
    dir: uploads/signatures
