spring:
  application:
    name: authentication-api

  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    jpa:
      repositories:
        enabled: true

  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com
      mail.transport.protocol: smtp
      mail.smtp.from: ${MAIL_USERNAME}

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /api

security:
  constant: ${SECURITY_CONSTANT}

frontend:
  url: ${FRONTEND_URL}

app:
  upload:
    dir: uploads/signatures